import React from 'react';

interface ConfigMessages {
  ctaText?: string;
}

interface InsightBoxProps {
  feedback: string;
  ctaText: string;
  onCTAClick: () => void;
  configMessages?: ConfigMessages;
}

/**
 * InsightBox component displays the AI feedback section
 * with a card containing the feedback and a call-to-action text
 * @param feedback - Feedback generated by AI about the user's profile
 * @param ctaText - Call-to-action text to encourage user to continue to Layer 2
 * @param onCTAClick - Callback function when CTA is clicked
 * @param configMessages - Optional configuration messages from CMS
 */
export const InsightBox: React.FC<InsightBoxProps> = ({ feedback, ctaText, onCTAClick, configMessages }) => {
  // Use CMS configured CTA text if available
  const displayCTAText = configMessages?.ctaText || ctaText;

  return (
    <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-200 rounded-xl p-6 shadow-md hover:shadow-lg transition-shadow duration-300">
      <div className="flex items-center mb-4">
        <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center text-white text-lg font-bold mr-3">
          🤖
        </div>
        <h2 className="text-xl font-semibold text-blue-800">
          Phân tích tổng quan của Tùng về hồ sơ của bạn
        </h2>
      </div>
      
      <div className="text-gray-700 leading-relaxed mb-6 bg-white bg-opacity-70 p-4 rounded-lg">
        <pre className="whitespace-pre-line">
          {feedback || "AI feedback sẽ hiển thị ở đây"}
        </pre>
      </div>
      
      <button
        className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white py-3 px-4 rounded-lg transition-all duration-300 shadow hover:shadow-lg transform hover:-translate-y-1 font-medium"
        onClick={onCTAClick}
      >
        {displayCTAText}
      </button>
    </div>
  );
};