import React from 'react';

interface InsightBoxProps {
  aiFeedback: string;
  ctaText: string;
}

/**
 * InsightBox component displays the AI feedback section
 * with a card containing the feedback and a call-to-action text
 * @param aiFeedback - Feedback generated by AI about the user's profile
 * @param ctaText - Call-to-action text to encourage user to continue to Layer 2
 */
export const InsightBox: React.FC<InsightBoxProps> = ({ aiFeedback, ctaText }) => {
  return (
    <div className="space-y-4">
      {/* AI Feedback Card */}
      <div className="bg-white border border-gray-200 rounded-xl shadow-sm p-6">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">
          Phân tích tổng quan của Tùng về hồ sơ của bạn
        </h2>
        <div className="text-gray-700 leading-relaxed">
          {aiFeedback || "AI feedback sẽ hiển thị ở đây"}
        </div>
      </div>
      
      {/* Call-to-Action Text */}
      <div className="text-gray-600 italic">
        {ctaText}
      </div>
    </div>
  );
};