import React from 'react';
import { useQuery } from 'convex/react';
import { api } from '../../../convex/_generated/api';
import { ResultBanner } from './ResultBanner';
import { InsightBox } from './InsightBox';
import { ScholarshipGrid } from './ScholarshipGrid';
import { ResultCTA } from './ResultCTA';

// Define the Scholarship interface
interface Scholarship {
  id: string;
  name: string;
  eligible: boolean;
  reasons: string[];
}

interface ResultPageProps {
  eligibleScholarships: Scholarship[];
  aiFeedback: string;
  cmsResultText?: string;
}

/**
 * ResultPage component displays scholarship eligibility results after completing the wizard
 * @param eligibleScholarships - List of scholarships the user is eligible for
 * @param aiFeedback - Feedback generated by AI about the user's profile
 * @param cmsResultText - Text content managed by admin through CMS
 */
export const ResultPage: React.FC<ResultPageProps> = ({
  eligibleScholarships,
  aiFeedback,
  cmsResultText,
}) => {
  // Get CMS configuration from the database
  const resultPageConfig = useQuery(api.resultPage.getResultPageConfig, {});
  
  // Determine if the user is eligible for any scholarships
  const hasEligibleScholarships = eligibleScholarships.length > 0;
  
  // Use CMS text if available, otherwise fall back to default
  const displayCTAText = cmsResultText || resultPageConfig?.ctaText || 
    "Đây chỉ là phân tích sơ bộ. Để biết rõ điểm mạnh/điểm yếu và cách cải thiện hồ sơ, hãy đi tiếp với Smart Profile Analysis.";
    
  // Use CMS fallback message if available, otherwise fall back to default
  const displayFallbackMessage = resultPageConfig?.fallbackMessage || 
    "Rất tiếc, hiện tại bạn chưa đủ điều kiện cho bất kỳ học bổng nào. Hãy thử lại sau khi cập nhật thêm thông tin.";
  
  // Handle navigation to Layer 2 (Smart Profile Analysis)
  const handleNavigateToLayer2 = () => {
    console.log("TODO: Navigate to Layer 2 - Smart Profile Analysis");
    // In a real application, this would navigate to the next step
    alert('Chuyển đến Layer 2 - Smart Profile Analysis (tính năng đang phát triển)');
  };
  
  // Handle navigation back to homepage
  const handleNavigateToHome = () => {
    console.log("Navigate back to homepage");
    // In a real application, this would navigate back to the home page
    window.location.href = '/';
  };
  
  return (
    <div className="max-w-6xl mx-auto px-4 py-10 space-y-8">
      {/* Banner Section */}
      <ResultBanner hasEligibleScholarships={hasEligibleScholarships} />
      
      {/* AI Feedback Section */}
      <InsightBox 
        aiFeedback={aiFeedback} 
        ctaText={displayCTAText}
      />
      
      {/* Scholarship Logos Grid */}
      <ScholarshipGrid 
        eligibleScholarships={eligibleScholarships} 
        onScholarshipClick={handleNavigateToLayer2}
        fallbackMessage={displayFallbackMessage}
      />
      
      {/* Call to Action Button */}
      <ResultCTA 
        hasEligibleScholarships={hasEligibleScholarships} 
        onContinue={handleNavigateToLayer2} 
        onBackToHome={handleNavigateToHome}
      />
    </div>
  );
};